import { Contact } from "./types/contact";
export const dummyData: Contact[] = [
  {
    id: "1",
    pic: "https://randomuser.me/api/portraits/men/74.jpg",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    notes: "Met at tech conference.",
    company: "IBM",
    todos: [],
  },
  {
    id: "2",
    pic: "https://randomuser.me/api/portraits/women/73.jpg",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+0987654321",
    notes: "Interested in software solution.",
    company: "IBM",
    todos: [],
  },
  {
    id: "3",
    pic: "https://randomuser.me/api/portraits/women/74.jpg",
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    phone: "+1122334455",
    notes: "Follow up on proposal.",
    company: "Microsoft",
    todos: [],
  },
  {
    id: "4",
    pic: "https://randomuser.me/api/portraits/men/75.jpg",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "+1223344556",
    notes: "Potential investor.",
    company: "Ycombinator",
    todos: [],
  },
  {
    id: "5",
    pic: "https://randomuser.me/api/portraits/women/75.jpg",
    name: "Linda Garcia",
    email: "linda.garcia@example.com",
    phone: "+1657986422",
    notes: "Requested product demo.",
    company: "Microsoft",
    todos: [
      {
        type: "call",
        description: "Follow up on product demo request.",
        done: false,
      },
      {
        type: "email",
        description: "Send initial product information.",
        done: false,
      },
      {
        type: "meeting",
        description: "Schedule product demo meeting for next week.",
        done: false,
      },
      {
        type: "task",
        description: "Prepare custom demo presentation.",
        done: false,
      },
    ],
  },
];
